version: '3.9'

services:
  twitter:
    container_name: twitter
    image: node:alpine
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
    networks:
      - nestjs-net
  db:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nestjs-net

volumes:
  pgdata: {}

networks:
  nestjs-net: